version: '3'

services:
  mongo_db:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - "9000:9000"  # Map port 3000 inside the container to port 9000 on the host machine
    environment:
      - APP_NAME=ExpensesApp
      - DATABASE_URL=mongodb+srv://fatenaalhussein:iq01y8iQLI4ldF6v@cluster0.wejqgds.mongodb.net/?retryWrites=true&w=majority
      - PASSWORD=iq01y8iQLI4ldF6v
      - PORT=3000     # Set the application's port to 3000
      - JWT_SECRET=faten

volumes:
  mongo_db:
