version: '3'

services:
  mongo_db:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - "9000:9000"  # Map port 3000 inside the container to port 9000 on the host machine
   
    env_file:
      - config.env
volumes:
  mongo_db:
