version: '3'

services:
  mongo_db:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - "9000:9000"  
   
    env_file:
      - config.env
volumes:
  mongo_db:
